import React, { useRef } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function BuyerQuotePDF({ quote }) {
  const pdfRef = useRef();

  const handleDownloadPDF = async () => {
    const input = pdfRef.current;
    const canvas = await html2canvas(input, { scale: 2 });
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pageWidth;
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`Quotation_${quote.quoteNumber || 'RFQ'}.pdf`);
  };

  return (
    <div className="flex flex-col items-center">
      <div ref={pdfRef} className="bg-white p-8 rounded-lg shadow max-w-2xl w-full border border-slate-200">
        <div className="text-center mb-6">
          <h2 className="text-2xl font-bold text-green-700 mb-1">SOFTWARE DEVELOPMENT PRICE QUOTE</h2>
          <div className="text-xs text-slate-500">(Company/Project Header)</div>
        </div>
        <div className="mb-4">
          <div className="flex flex-wrap gap-8 text-sm">
            <div>
              <div><b>Company Name:</b> {quote.companyName}</div>
              <div><b>Address:</b> {quote.companyAddress}</div>
              <div><b>Email:</b> {quote.companyEmail}</div>
              <div><b>Contact Number:</b> {quote.companyContact}</div>
              <div><b>Website:</b> {quote.companyWebsite}</div>
            </div>
            <div>
              <div><b>Customer Name:</b> {quote.customerName}</div>
              <div><b>Address:</b> {quote.customerAddress}</div>
              <div><b>Email:</b> {quote.customerEmail}</div>
              <div><b>Contact Number:</b> {quote.customerContact}</div>
              <div><b>Quote Number:</b> {quote.quoteNumber}</div>
              <div><b>Valid Dates:</b> {quote.validDates}</div>
            </div>
          </div>
        </div>
        <div className="border-t border-b border-green-400 py-2 my-4">
          <table className="w-full text-sm">
            <thead>
              <tr className="bg-green-200 text-green-900">
                <th className="py-1 px-2 text-left">ITEM</th>
                <th className="py-1 px-2 text-right">QUANTITY</th>
                <th className="py-1 px-2 text-right">PRICE</th>
                <th className="py-1 px-2 text-right">TOTAL</th>
              </tr>
            </thead>
            <tbody>
              {quote.items.map((item, idx) => (
                <tr key={idx} className="border-b last:border-b-0">
                  <td className="py-1 px-2">{item.name}</td>
                  <td className="py-1 px-2 text-right">{item.quantity}</td>
                  <td className="py-1 px-2 text-right">${item.price.toFixed(2)}</td>
                  <td className="py-1 px-2 text-right">${(item.price * item.quantity).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr>
                <td colSpan={3} className="text-right font-semibold">SUB TOTAL</td>
                <td className="text-right">${quote.subTotal.toFixed(2)}</td>
              </tr>
              <tr>
                <td colSpan={3} className="text-right font-semibold">TAX</td>
                <td className="text-right">${quote.tax.toFixed(2)}</td>
              </tr>
              <tr>
                <td colSpan={3} className="text-right font-semibold">DISCOUNT</td>
                <td className="text-right">${quote.discount.toFixed(2)}</td>
              </tr>
              <tr className="bg-green-100">
                <td colSpan={3} className="text-right font-bold">GRAND TOTAL</td>
                <td className="text-right font-bold">${quote.grandTotal.toFixed(2)}</td>
              </tr>
            </tfoot>
          </table>
        </div>
        <div className="text-xs text-slate-400 text-center mt-4">Generated by ADA Platform</div>
      </div>
      <button
        onClick={handleDownloadPDF}
        className="mt-6 px-6 py-2 bg-green-600 text-white rounded shadow hover:bg-green-700 transition"
      >
        Download as PDF
      </button>
    </div>
  );
}
